config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root to: redirect('namespaces')

  resources :namespaces, only: [:index] do
    resources :pods, only: [:index, :destroy]
  end

  get :add_cat_fact_to_pod, to: 'pods#addCatFact'
end

app/models/concerns/kubernetes.rb
module Kubernetes
    extend ActiveSupport::Concern

    class_methods do
        def kubernetes_client
            K8s::Client.config(
                K8s::Config.new(YAML.safe_load(`kubectl config view --minify --raw=true`)),
                ssl_verify_peer: false
            )
        end
    end

    included do
        attr_accessor :resource
        delegate :metadata, :spec, :status, to: :resource
        delegate :kubernetes_client, to: :class

        def initialize(resource)
            @resource = resource
        end

        def id
            @resource.metadata.name
        end
    end
end

app/models/namespace.rb
class Namespace
    include ActiveModel::Model
    include Kubernetes

    def self.all
        kubernetes_client.api.resource('namespaces').list.map { |n| Namespace.new(n) }
    end
end

app/models/pod.rb
class Pod
    include ActiveModel::Model
    include Kubernetes

    def self.all(namespace)
        kubernetes_client.api('v1').resource('pods', namespace: namespace).list.map do |pod|
            Pod.new pod
        end
    end

    def self.find(namespace, name)
        Pod.new kubernetes_client.api('v1').resource('pods', namespace: namespace).get(name)
    end

    def save
        kubernetes_client.api('v1').resource('pods', namespace: metadata.namespace).update_resource(@resource)
    end

    def destroy!
        kubernetes_client.api('v1').resource('pods', namespace: metadata.namespace).delete(metadata.name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/concerns/cat_fact_concern.rb
module CatFactConcern
    extend ActiveSupport::Concern

    included do
        def get_cat_fact(_)
            api = Faraday.get("https://catfact.ninja/fact").body
            puts "got the api"
            json = JSON.parse(api)
            puts "got the json"
            json.deep_symbolize_keys[:fact]
        rescue
            "Cats always land on their feet"
        end
    end
end

app/controllers/namespaces_controller.rb
class NamespacesController < ApplicationController
  # GET /namespaces or /namespaces.json
  def index
    @namespaces = Namespace.all
  end
end

app/controllers/pods_controller.rb
class PodsController < ApplicationController
  include CatFactConcern

  before_action :set_pod, only: %i[ addCatFact destroy ]

  API_KEY = "1234567890-SECRET-KEY"

  # GET /pods or /pods.json
  def index
    @pods = Pod.all params[:namespace_id]
  end

  # DELETE /pods/1 or /pods/1.json
  def destroy
    @pod.destroy!

    respond_to do |format|
      format.html { redirect_to namespace_pods_path, status: :see_other, notice: "Pod #{@pod.id} was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # ADD /cat_fact
  def addCatFact()
    @pod.metadata.annotations.cat_fact = get_cat_fact(API_KEY)
    @pod.save

    redirect_to namespace_pods_path(params[:namespace_id], params[:id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pod
      @pod = Pod.find(params[:namespace_id], params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pod_params
      params.fetch(:pod, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/namespaces_helper.rb
module NamespacesHelper
end

app/helpers/pods_helper.rb
module PodsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Pod Restarter" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/namespaces/_namespace.html.erb
<span id="<%= dom_id namespace %>">
    <%= namespace.metadata.name %>
</span>

app/views/namespaces/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Namespaces" %>

<h1>Namespaces</h1>

<div id="namespaces">
  <% @namespaces.each do |namespace| %>
    <p>
      <%= render namespace %>
      <%= link_to "Show pods", namespace_pods_path(namespace.id) %>
    </p>
  <% end %>
</div>

app/views/pods/_pod.html.erb
<div id="<%= dom_id pod %>">
    <h2><%= pod.metadata.name %></h2>
    <p>
        Labels:
        <% pod.metadata.labels.to_h.each do |label, value| %>
            <span class="metadata">
                <%= label %>: <%=value%>
            </span>
        <% end %>
    </p>
    <p>
        Annotations:
        <% pod.metadata.annotations.to_h.each do |label, value| %>
            <span class="metadata">
                <%= label %>: <%=value%>
            </span>
        <% end %>
    </p>
    <p>
        Cat fact: <span class="metadata" style="background: green"><%= pod.metadata.annotations.cat_fact %>
    <p>
        Containers:
        <% pod.status.containerStatuses.each do |container| %>
            <span class="metadata">
                <%= container.name %>: <%= container.state.to_h.keys.first %>
            </span>
        <% end %>
    </p>
</div>

app/views/pods/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Pods" %>

<h1>
  Pods in <%= params[:namespace_id] %>
  <%= link_to "(back)", namespaces_path %>
</h1>

<div id="pods">
  <% @pods.each do |pod| %>
    <p>
      <%= render pod %>
      <%= link_to "Add cat fact", add_cat_fact_to_pod_path(namespace_id: pod.metadata.namespace, id: pod.id) %>
      <%= button_to "Restart this pod", namespace_pod_path(pod.metadata.namespace, pod.id), method: :delete %>
    </p>
  <% end %>
</div>